# Generated by Django 5.1.1 on 2024-12-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0003_alter_cuttransfer_id_alter_fabric_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuttransfer',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='returntransfer',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='التاريخ'),
        ),
    ]
