# Generated by Django 5.1.1 on 2024-12-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0005_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
