# Generated by Django 5.1.1 on 2025-01-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0006_alter_updates_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuttransfer',
            name='roll',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الاتواب'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='roll',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الاتواب'),
        ),
        migrations.AlterField(
            model_name='returntransfer',
            name='roll',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الاتواب'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='roll',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الاتواب'),
        ),
    ]
