# Generated by Django 5.1.1 on 2025-01-19 10:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='الرمز')),
                ('model_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الموديل')),
                ('pieces_count', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='قطع الموديل')),
                ('carton_count', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(12)], verbose_name='قطع الكرتون')),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='النوع')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.model', verbose_name='الموديل')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='الرمز')),
                ('size_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='المقاس')),
                ('amount', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الكمية')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.model', verbose_name='الموديل')),
            ],
        ),
    ]
