# Generated by Django 5.1.1 on 2025-01-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='carton_count',
        ),
        migrations.RemoveField(
            model_name='model',
            name='pieces_count',
        ),
        migrations.AddField(
            model_name='piece',
            name='amount',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='الكمية'),
        ),
        migrations.AddField(
            model_name='piece',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='المقاس'),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
