# Generated by Django 5.1.1 on 2025-01-20 05:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_remove_model_carton_count_remove_model_pieces_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piece',
            name='amount',
        ),
        migrations.AddField(
            model_name='model',
            name='pieces_count',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='قطع الموديل'),
        ),
        migrations.AddField(
            model_name='piece',
            name='available_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='الكمية المتبقية'),
        ),
        migrations.AddField(
            model_name='piece',
            name='used_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='الكمية المستخدمة'),
        ),
        migrations.AlterField(
            model_name='model',
            name='model_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='رقم الموديل'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='production.model', verbose_name='الموديل'),
        ),
        migrations.CreateModel(
            name='SizeAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=50, null=True, verbose_name='المقاس')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='الكمية')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_amounts', to='production.model', verbose_name='الموديل')),
            ],
        ),
    ]
