# Generated by Django 5.1.1 on 2025-01-20 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_remove_piece_amount_model_pieces_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='pieces_count',
        ),
    ]
