# Generated by Django 5.1.1 on 2025-01-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_remove_model_pieces_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='model_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم الموديل'),
        ),
    ]
