# Generated by Django 5.1.1 on 2025-01-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_alter_model_model_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='used_amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='الكمية المستخدمة'),
        ),
    ]
