# Generated by Django 5.1.1 on 2025-01-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_alter_piece_used_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='available_amount',
            field=models.IntegerField(blank=True, default=0, verbose_name='الكمية المتبقية'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='size',
            field=models.CharField(blank=True, max_length=50, verbose_name='المقاس'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='type',
            field=models.CharField(blank=True, max_length=50, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='used_amount',
            field=models.IntegerField(blank=True, default=0, verbose_name='الكمية المستخدمة'),
        ),
        migrations.AlterField(
            model_name='sizeamount',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='sizeamount',
            name='size',
            field=models.CharField(max_length=50, verbose_name='المقاس'),
        ),
        migrations.AlterUniqueTogether(
            name='sizeamount',
            unique_together={('model', 'size')},
        ),
    ]
