# Generated by Django 5.0.7 on 2025-01-24 12:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_alter_piece_available_amount_alter_piece_size_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model',
            options={'ordering': ['model_number']},
        ),
        migrations.AlterModelOptions(
            name='piece',
            options={'ordering': ['size', 'type']},
        ),
        migrations.AlterModelOptions(
            name='sizeamount',
            options={'ordering': ['size']},
        ),
        migrations.AddField(
            model_name='model',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
