# Generated by Django 5.1.1 on 2025-01-25 09:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_alter_model_options_alter_piece_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
        ),
    ]
