# Generated by Django 5.1.1 on 2025-01-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_alter_model_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='sizeamount',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
