# Generated by Django 5.1.1 on 2025-01-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_productionpiece'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionpiece',
            name='factory',
            field=models.CharField(blank=True, max_length=50, verbose_name='المصنع'),
        ),
    ]
