# Generated by Django 5.1.1 on 2025-02-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_alter_productionpiece_options_model_is_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionpiece',
            name='comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='الملاحظات'),
        ),
    ]
