# Generated by Django 5.1.1 on 2025-02-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_productionpiece_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء'),
        ),
    ]
