# Generated by Django 5.1.1 on 2025-02-13 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_model_ended_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='Packing_per_carton',
            field=models.PositiveIntegerField(choices=[(12, '1'), (24, '2'), (36, '3'), (48, '4')], default=12, verbose_name='الدست في الكرتونة'),
        ),
        migrations.CreateModel(
            name='carton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.PositiveIntegerField(verbose_name='الطول')),
                ('width', models.PositiveIntegerField(verbose_name='العرض')),
                ('height', models.PositiveIntegerField(verbose_name='الارتفاع')),
                ('comment', models.CharField(blank=True, max_length=100, verbose_name='الملاحظات')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartons', to='production.model', verbose_name='الموديل')),
            ],
        ),
    ]
