# Generated by Django 5.1.1 on 2025-02-14 04:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_model_packing_per_carton_carton'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='packing_available_amount',
            field=models.IntegerField(blank=True, default=0, verbose_name='الكمية المتبقية للتعبئة'),
        ),
        migrations.AddField(
            model_name='piece',
            name='packing_used_amount',
            field=models.IntegerField(blank=True, default=0, verbose_name='الكمية المستخدمة للتعبئة'),
        ),
        migrations.CreateModel(
            name='Packing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('used_amount', models.IntegerField(blank=True, default=0, verbose_name='الكمية للتعبئة')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Packings', to='production.piece', verbose_name='القطعة')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
