# Generated by Django 5.1.1 on 2025-02-14 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0018_alter_carton_height_alter_carton_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packing',
            name='carton',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Packings', to='production.carton', verbose_name='الكرتونة'),
        ),
    ]
