# Generated by Django 5.1.1 on 2025-02-14 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0019_packing_carton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packing',
            name='carton',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Packings', to='production.carton', verbose_name='الكرتونة'),
        ),
    ]
