# Generated by Django 5.1.1 on 2025-02-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0020_alter_packing_carton'),
    ]

    operations = [
        migrations.AddField(
            model_name='packing',
            name='used_carton',
            field=models.IntegerField(default=0, verbose_name='الكرتون للتعبئة'),
        ),
        migrations.AlterField(
            model_name='packing',
            name='used_amount',
            field=models.IntegerField(default=0, verbose_name='الكمية للتعبئة'),
        ),
    ]
