# Generated by Django 5.1.1 on 2025-02-14 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0024_alter_carton_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packing',
            name='piece',
        ),
        migrations.RemoveField(
            model_name='packing',
            name='used_amount',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='packing_available_amount',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='packing_used_amount',
        ),
        migrations.AddField(
            model_name='model',
            name='available_carton',
            field=models.IntegerField(blank=True, default=0, verbose_name='الكراتين المتبقية'),
        ),
        migrations.AddField(
            model_name='model',
            name='used_carton',
            field=models.IntegerField(blank=True, default=0, verbose_name='الكراتين المستخدمة'),
        ),
        migrations.AddField(
            model_name='packing',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packings', to='production.model', verbose_name='الموديل'),
        ),
        migrations.AlterField(
            model_name='packing',
            name='carton',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packings', to='production.carton', verbose_name='الكرتونة'),
        ),
    ]
