# Generated by Django 5.1.1 on 2025-02-14 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0025_remove_packing_piece_remove_packing_used_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packing',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packings', to='production.model', verbose_name='الموديل'),
        ),
    ]
