# Generated by Django 5.1.1 on 2025-02-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0026_alter_packing_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packing',
            name='used_carton',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='الكرتون للتعبئة'),
        ),
    ]
