# Generated by Django 5.1.1 on 2025-02-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0027_alter_packing_used_carton'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='is_shipped',
            field=models.BooleanField(default=False),
        ),
    ]
