# Generated by Django 5.1.1 on 2025-02-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0029_alter_model_packing_per_carton'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الشحن'),
        ),
    ]
