# Generated by Django 5.1.1 on 2025-02-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0030_model_shipped_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='carton',
            name='type',
            field=models.CharField(choices=[('شماعة', 'شماعة'), ('تطبيق', 'تطبيق')], default='تطبيق', max_length=10, verbose_name='النوع'),
        ),
    ]
