# Generated by Django 5.1.1 on 2025-02-15 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0032_remove_model_packing_per_carton_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packing',
            name='size_amount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packings', to='production.sizeamount', verbose_name='المقاس'),
        ),
    ]
