# Generated by Django 5.1.1 on 2025-02-15 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0033_packing_size_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packing',
            name='size_amount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packings', to='production.sizeamount', verbose_name='المقاس'),
        ),
    ]
