# Generated by Django 5.1.1 on 2025-03-06 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0035_remove_packing_size_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='اسم المصنع')),
                ('statue', models.PositiveIntegerField(choices=[(1, 'يعمل'), (2, 'متوقف'), (3, 'منتهي')], default=1, verbose_name='الحاله')),
            ],
        ),
        migrations.AddField(
            model_name='productionpiece',
            name='worked_factory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='production.factory', verbose_name='المصنع'),
        ),
    ]
