# Generated by Django 5.1.1 on 2025-02-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagstock',
            name='bags_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد الاكياس'),
        ),
        migrations.AddField(
            model_name='bagstock',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='التاريخ'),
        ),
        migrations.AddField(
            model_name='bagsupplies',
            name='bags_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد الاكياس'),
        ),
        migrations.AddField(
            model_name='cartonstock',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='التاريخ'),
        ),
        migrations.AddField(
            model_name='gluestock',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='التاريخ'),
        ),
        migrations.AddField(
            model_name='hangerstock',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='التاريخ'),
        ),
        migrations.AddField(
            model_name='hangtagstock',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='التاريخ'),
        ),
        migrations.AddField(
            model_name='heatsealstock',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='التاريخ'),
        ),
        migrations.AddField(
            model_name='kardonstock',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='التاريخ'),
        ),
        migrations.AddField(
            model_name='packagingbag',
            name='bags_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد الاكياس'),
        ),
        migrations.AddField(
            model_name='returnbag',
            name='bags_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد الاكياس'),
        ),
        migrations.AddField(
            model_name='rubberstock',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='التاريخ'),
        ),
        migrations.AddField(
            model_name='sizerstock',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='التاريخ'),
        ),
        migrations.AddField(
            model_name='threadstock',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='التاريخ'),
        ),
        migrations.AddField(
            model_name='ticketpricestock',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='التاريخ'),
        ),
        migrations.AddField(
            model_name='ticketsatanstock',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='التاريخ'),
        ),
        migrations.AddField(
            model_name='ticketstock',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='bagstock',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='الوزن'),
        ),
        migrations.AlterField(
            model_name='bagsupplies',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='الوزن'),
        ),
        migrations.AlterField(
            model_name='packagingbag',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='الوزن'),
        ),
        migrations.AlterField(
            model_name='returnbag',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='الوزن'),
        ),
    ]
