# Generated by Django 5.1.1 on 2025-02-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0002_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagstock',
            name='bag_length',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مقاس الكيس (الطول)'),
        ),
        migrations.AlterField(
            model_name='bagstock',
            name='bag_width',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مقاس الكيس (العرض)'),
        ),
        migrations.AlterField(
            model_name='bagsupplies',
            name='bag_length',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مقاس الكيس (الطول)'),
        ),
        migrations.AlterField(
            model_name='bagsupplies',
            name='bag_width',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مقاس الكيس (العرض)'),
        ),
        migrations.AlterField(
            model_name='cartonstock',
            name='height',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='المقاس (الارتفاع)'),
        ),
        migrations.AlterField(
            model_name='cartonstock',
            name='length',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='المقاس (الطول)'),
        ),
        migrations.AlterField(
            model_name='cartonstock',
            name='width',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='المقاس (العرض)'),
        ),
        migrations.AlterField(
            model_name='cartonsupplies',
            name='height',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='المقاس (الارتفاع)'),
        ),
        migrations.AlterField(
            model_name='cartonsupplies',
            name='length',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='المقاس (الطول)'),
        ),
        migrations.AlterField(
            model_name='cartonsupplies',
            name='width',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='المقاس (العرض)'),
        ),
        migrations.AlterField(
            model_name='gluestock',
            name='width',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عرض اللزق'),
        ),
        migrations.AlterField(
            model_name='gluesupplies',
            name='width',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عرض اللزق'),
        ),
        migrations.AlterField(
            model_name='packagingbag',
            name='bag_length',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مقاس الكيس (الطول)'),
        ),
        migrations.AlterField(
            model_name='packagingbag',
            name='bag_width',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مقاس الكيس (العرض)'),
        ),
        migrations.AlterField(
            model_name='packagingcarton',
            name='height',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='المقاس (الارتفاع)'),
        ),
        migrations.AlterField(
            model_name='packagingcarton',
            name='length',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='المقاس (الطول)'),
        ),
        migrations.AlterField(
            model_name='packagingcarton',
            name='width',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='المقاس (العرض)'),
        ),
        migrations.AlterField(
            model_name='packagingglue',
            name='width',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عرض اللزق'),
        ),
        migrations.AlterField(
            model_name='packagingrubber',
            name='width',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عرض الاستك'),
        ),
        migrations.AlterField(
            model_name='packagingticketsatan',
            name='cotton_percentage',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نسبة القطن'),
        ),
        migrations.AlterField(
            model_name='packagingticketsatan',
            name='polyester_percentage',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نسبة البوليستر'),
        ),
        migrations.AlterField(
            model_name='returnbag',
            name='bag_length',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مقاس الكيس (الطول)'),
        ),
        migrations.AlterField(
            model_name='returnbag',
            name='bag_width',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مقاس الكيس (العرض)'),
        ),
        migrations.AlterField(
            model_name='returncarton',
            name='height',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='المقاس (الارتفاع)'),
        ),
        migrations.AlterField(
            model_name='returncarton',
            name='length',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='المقاس (الطول)'),
        ),
        migrations.AlterField(
            model_name='returncarton',
            name='width',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='المقاس (العرض)'),
        ),
        migrations.AlterField(
            model_name='returnrubber',
            name='width',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عرض الاستك'),
        ),
        migrations.AlterField(
            model_name='returnticketsatan',
            name='cotton_percentage',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نسبة القطن'),
        ),
        migrations.AlterField(
            model_name='returnticketsatan',
            name='polyester_percentage',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نسبة البوليستر'),
        ),
        migrations.AlterField(
            model_name='rubberstock',
            name='width',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عرض الاستك'),
        ),
        migrations.AlterField(
            model_name='rubbersupplies',
            name='width',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عرض الاستك'),
        ),
        migrations.AlterField(
            model_name='ticketsatanstock',
            name='cotton_percentage',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نسبة القطن'),
        ),
        migrations.AlterField(
            model_name='ticketsatanstock',
            name='polyester_percentage',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نسبة البوليستر'),
        ),
        migrations.AlterField(
            model_name='ticketsatansupplies',
            name='cotton_percentage',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نسبة القطن'),
        ),
        migrations.AlterField(
            model_name='ticketsatansupplies',
            name='polyester_percentage',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نسبة البوليستر'),
        ),
    ]
